import { defineField, defineType } from 'sanity';

export const blogIndexPageType = defineType({
  name: 'blogIndexPage',
  title: 'Blog Index Page',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Hero' },
    { name: 'featured', title: 'Featured Post' },
    { name: 'grid', title: 'Grid Labels' },
    { name: 'empty', title: 'Empty State' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'heroEyebrow',
      title: 'Hero Eyebrow',
      type: 'string',
      group: 'hero',
      initialValue: 'Field Notes',
    }),
    defineField({
      name: 'heroHeadline',
      title: 'Hero Headline',
      type: 'string',
      group: 'hero',
      initialValue: 'Field Notes',
    }),
    defineField({
      name: 'heroSubheading',
      title: 'Hero Subheading',
      type: 'text',
      rows: 2,
      group: 'hero',
      initialValue:
        'Notes from the clinic on ketamine treatment, integration, and the science behind it.',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroImageCaption',
      title: 'Hero Image Caption',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroImageAlt',
      title: 'Hero Image Alt Text',
      type: 'string',
      group: 'hero',
      initialValue: 'Field Notes hero photo',
    }),
    defineField({
      name: 'featuredPost',
      title: 'Featured Post',
      description: 'Shown large at the top of the index. Pick from existing Blog Posts.',
      type: 'reference',
      to: [{ type: 'blogPost' }],
      group: 'featured',
    }),
    defineField({
      name: 'featuredEyebrow',
      title: 'Featured Eyebrow',
      type: 'string',
      group: 'featured',
      initialValue: 'Featured',
    }),
    defineField({
      name: 'featuredCtaLabel',
      title: 'Featured CTA Label',
      type: 'string',
      group: 'featured',
      initialValue: 'Read the note →',
    }),
    defineField({
      name: 'gridHeadingWithFeatured',
      title: 'Grid Heading (when a featured post is set)',
      type: 'string',
      group: 'grid',
      initialValue: 'More notes',
    }),
    defineField({
      name: 'gridHeadingNoFeatured',
      title: 'Grid Heading (no featured post)',
      type: 'string',
      group: 'grid',
      initialValue: 'All notes',
    }),
    defineField({
      name: 'noteCountSingular',
      title: 'Note Count Label (singular)',
      type: 'string',
      group: 'grid',
      initialValue: 'note',
    }),
    defineField({
      name: 'noteCountPlural',
      title: 'Note Count Label (plural)',
      type: 'string',
      group: 'grid',
      initialValue: 'notes',
    }),
    defineField({
      name: 'cardCtaLabel',
      title: 'Card CTA Label',
      type: 'string',
      group: 'grid',
      initialValue: 'Read →',
    }),
    defineField({
      name: 'emptyHeadline',
      title: 'Empty-State Headline',
      type: 'string',
      group: 'empty',
      initialValue: 'New notes coming soon.',
    }),
    defineField({
      name: 'emptyBody',
      title: 'Empty-State Body',
      type: 'text',
      rows: 2,
      group: 'empty',
      initialValue:
        'Katie and Christa are working on the first batch. Check back in a couple weeks.',
    }),
    defineField({
      name: 'metaTitle',
      title: 'Meta Title (browser tab + SEO)',
      type: 'string',
      group: 'seo',
      initialValue: 'Field Notes — Phos',
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description',
      type: 'text',
      rows: 2,
      group: 'seo',
      initialValue:
        'Notes from the clinic on ketamine treatment, integration, and the science behind it.',
    }),
  ],
  preview: {
    select: { title: 'heroHeadline' },
    prepare: ({ title }) => ({ title: title ?? 'Blog Index Page' }),
  },
});
